CREATE DATABASE IF NOT EXISTS ledtasterdb;
USE ledtasterdb;

CREATE TABLE IF NOT EXISTS states(
    id int NOT NULL AUTO_INCREMENT,
    state BOOLEAN NOT NULL,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);